### ISSUE TITLE
Missing amd64 libarchive.so.7

### ISSUE THREAD

**Issue by VincentBentley** [dfr/freebsd-images#4]
I built the FreeBSD container images today on a FreeBSD 14.1p5 (amd64) host. I created a simple Containerfile that only runs pkg update during the build via a docker-compose.yaml . The container build failed with the following error:

```
$ sudo podman-compose up --build
STEP 1/3: FROM localhost/freebsd14.1-small:latest
STEP 2/3: RUN pkg update
ld-elf.so.1: Shared object "libarchive.so.7" not found, required by "pkg"
Error: building at STEP "RUN pkg update": while running runtime: exit status 1
ERROR:podman_compose:Build command failed
```

I wasn't expecting any difference running buildah directly, and the result confirmed this.

```
$ sudo buildah build .
STEP 1/3: FROM localhost/freebsd14.1-small:latest
STEP 2/3: RUN pkg update
ld-elf.so.1: Shared object "libarchive.so.7" not found, required by "pkg"
Error: building at STEP "RUN pkg update": while running runtime: exit status 1

```
I changed 'RUN pkg update' to 'RUN freebsd-version' and this works fine.

```
$ sudo podman-compose up --build
STEP 1/3: FROM localhost/freebsd14.1-small:latest
STEP 2/3: RUN freebsd-version
14.1-RELEASE-p5
--> b3cc27e39c73
STEP 3/3: CMD [ "sh" ]
COMMIT fbsd_test
--> d9b86f2700aa
Successfully tagged localhost/fbsd_test:latest

```

I am using the latest FreeBSD pkg repo to workaround the nil pointer reference that initially prevented building. I tried using 'RUN pkg-static bootstrap' but it is not in the image. I then executed the image with a shell in an interactive terminal. I had a look around and found the missing library in /usr/lib32/libarchive.so.7 but there is no 64-bit equivalent in the image.

**Comment by dfr** [comment]
I pushed a fix for this earlier today - if you are still seeing problems, can you let me know the git hash of the version of freebsd-images you used to build your image set.

**Comment by VincentBentley** [comment]
I pulled up to commit a3d514d2d69e3266d374edbe64e6251d1e37102a

The missing libarchive appears to be resolved.

I am now getting a 404 error when pkg attempts to bootstrap https://pkg.freebsd.org/FreeBSD:14:amd64/base_release_1/Latest/pkg.txz . The folder 'Latest' does not appear to exist, perhaps a missing symbolic link on the repo?

The image actually times out and reports the following in an interactive terminal:

```
Bootstrapping pkg from pkg+https://pkg.freebsd.org/FreeBSD:14:amd64/base_release_1, please wait...
pkg: Error fetching https://pkg.freebsd.org/FreeBSD:14:amd64/base_release_1/Latest/pkg.txz: Address family for host not supported
Address resolution failed for https://pkg.freebsd.org/FreeBSD:14:amd64/base_release_1.
Consider changing PACKAGESITE.

```

I get the 404 error when I try the URL in a browser.

**Comment by dfr** [comment]
The pkgbase repositories don't have pkg.txz in them - when I have pkgbase enabled, I have to use 'pkg bootstrap -r FreeBSD' so that it downloads pkg from the right place. I'm not sure if this is related to your problem though - the DNS timeout is new to me.

Do you have a simple recipe for reproducing this?

**Comment by VincentBentley** [comment]
Sorry, I have been away on a family emergency since my last post. I will have time to test again tomorrow (Monday 7th).

**Comment by VincentBentley** [comment]
The pkg.txz is missing from the FreeBSD amd64 repo. I have raised a bug report with FreeBSD.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281924

**Comment by VincentBentley** [comment]
I am fairly certain that my problem is in my network config. I can fetch pkg.pkg from the console of my Podman host but not from an image running on that host. The host has multiple vlans and bridges so it's likely that I have messed something up with the PF NAT configuration. I will build a specific host for testing Podman that has a very basic wired network config and prove that I can fetch pkg.pkg from a running image before going further.

**Comment by VincentBentley** [comment]
Closing this issue as the libarchive.so.7 problem has been resolved.
